# SPDX-FileCopyrightText: 2024-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: khangman
confinement: strict
grade: stable
base: core24
adopt-info: khangman
apps:
  khangman:
    extensions:
      - kde-neon-6
    common-id: org.kde.khangman.desktop
    desktop: usr/share/applications/org.kde.khangman.desktop
    command: usr/bin/khangman
    plugs:
      - audio-playback
    environment:
      QT_MEDIA_BACKEND: "ffmpeg"
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy${LD_LIBRARY_PATH}
      PATH: $SNAP/ffmpeg-platform/usr/bin:$SNAP/usr/bin${PATH}
      XDG_DATA_DIRS: "$XDG_DATA_DIRS:$SNAP/usr/share"
      XDG_CONFIG_DIRS: "$XDG_CONFIG_DIRS:$SNAP/etc/xdg"
plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.khangman
    bus: session
parts:
  libkeduvocdocument:
    plugin: cmake
    source: https://invent.kde.org/education/libkeduvocdocument.git
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    stage-packages:
      - rsync
      - libpopt0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    override-stage: |
        craftctl default
        rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  khangman:
    after:
      - libkeduvocdocument
    parse-info:
      - usr/share/metainfo/org.kde.khangman.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libxml2-dev
      - gettext
      - doxygen
      - graphviz
      - libxml2-utils
      - docbook-xml
      - docbook-xsl
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  kdeedu-data:
    source: https://invent.kde.org/education/kdeedu-data.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
  gpu-2404:
    after: [khangman]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - khangman
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
